# Generated by Django 5.1.4 on 2024-12-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='original_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_image', models.ImageField(upload_to='result_photos/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('parking_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_result', to='detection.parkingphoto')),
            ],
        ),
        migrations.CreateModel(
            name='FilteredPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_step', models.IntegerField()),
                ('filtered_image', models.ImageField(upload_to='filtered_photos/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('parking_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtered_photos', to='detection.parkingphoto')),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessedImage',
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
